name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
            mysql-version: "8.0"
            root-password: "1234"
      - name: Test MySQL connection
        run: mysql -uroot -p1234 -e 'SELECT version()'
      - name: Wait for MySQL to be ready
        run: |
            echo "Waiting for MySQL to be ready...."
            until mysqladmin ping --silent; do
              echo "Waiting for the database connection..."
              sleep 5
            done
            echo "MySQL is ready!"
      - name: Verify MySQL installation
        run: mysql -uroot -p1234 -e "SHOW DATABASES;"
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
      - name: Run tests
        run: mvn test