name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create database
        run: docker run -d --name my-db -e MYSQL_ROOT_PASSWORD=1234 mysql:latest
      - name: Set environment variable
        run: echo "DOCKER_DB_NAME=my-db" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
      - name: Run tests
        run: mvn test
      - name: Stop database
        run: docker stop my-db && docker rm my-db