name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create Docker network
        run: docker network create my-network
      - name: Check if my.conf exists
        run: ls -l docker/config/my.conf
      - name: Create database
        run: |
          docker run -d --name my-db --network my-network --hostname my-db \
            -e MYSQL_ROOT_PASSWORD=1234 \
            -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
            -v ${{ github.workspace }}/docker/config/my.conf:/etc/mysql/conf.d/config-file.cnf \
            mysql:latest
          docker exec -it my-db mysql -u root -p1234 -e "CREATE USER 'myuser'@'%' IDENTIFIED BY 'mypassword'; GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'%'; FLUSH PRIVILEGES;"
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until docker exec my-db mysqladmin ping --silent; do
            echo "Waiting for the database connection..."
            sleep 5
          done
      - name: Test MySQL connection using MySQL client
        run: docker exec my-db mysql --user=root --password=1234 --execute="SHOW DATABASES;"
      - name: Set environment variable
        run: echo "DOCKER_DB_NAME=my-db" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
      - name: Run tests
        run: mvn test
      - name: Stop database
        run: docker stop my-db && docker rm my-db